# services:
#     app:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         container_name: whisperbox_app
#         ports:
#             - "8000:8000"
#         env_file:
#             - .env.prod
#         depends_on:
#             - db
#         restart: unless-stopped

#     db:
#         image: postgres:16-alpine
#         container_name: whisperbox_db
#         environment:
#             POSTGRES_USER: postgres
#             POSTGRES_PASSWORD: postgres
#             POSTGRES_DB: whisperboxapi
#         volumes:
#             - pgdata:/var/lib/postgresql/data
#         restart: unless-stopped
# volumes:
#     pgdata:
